name: Deploy to Amazon S3

on:
  workflow_dispatch: # Manual trigger
  push:
    branches: ["master"]

env:
  AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
  AWS_REGION: eu-north-1
  S3_BUCKET_NAME: fps.carlssonk.com
  APP_NAME: fps

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: ${{ github.event_name == 'pull_request' && github.base_ref || github.ref_name }}
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Set Env Variables
      run: |
        echo "IAM_ROLE_NAME=${{ env.APP_NAME }}-deploy-role" >> $GITHUB_ENV

    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS Credentials (OIDC)
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.IAM_ROLE_NAME }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Deploy to S3
      run: |
        aws s3 sync dist/ s3://${{ env.S3_BUCKET_NAME }} --delete